routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\ElchilarController;
use App\Http\Controllers\EnterExitController;
use App\Http\Controllers\GroupTestsController;
use App\Http\Controllers\IntegrationController;
use App\Http\Controllers\LessonsController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\RaspisaniyaController;
use App\Http\Controllers\ShogirdController;
use App\Http\Controllers\StatisticController;
use App\Http\Controllers\TestCheckController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\UserCheckController;
use App\Http\Controllers\UsersAllController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\UsersPageController;
use App\Http\Controllers\VideoController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => '/'], function () {
    Route::get('/register', [AuthController::class, 'registerView'])->name('register-view');
    Route::post('/register', [AuthController::class, 'register'])->name('register');

    Route::get('/', [AuthController::class, 'loginView'])->name('login');
    Route::get('/login', [AuthController::class, 'loginView'])->name('login-view');
    Route::post('/login-check', [AuthController::class, 'LoginCheck'])->name('login-check');

    Route::get('/users-region', [AuthController::class, 'ChooseRegion'])->name('users-region');

    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
});


Route::group(['prefix' => 'admin','middleware' => ['auth', 'userAdminRole:admin,assistant']], function () {
    Route::get('/', [AdminController::class, 'admin'])->name('admin');
    Route::resource('users', UsersController::class);
    Route::resource('new_user', UsersAllController::class);
    Route::resource('users_check', UserCheckController::class);
    Route::get('/integration',[IntegrationController::class,'index'])->name('integration');
    Route::get('/jang_matrix/{id}',[IntegrationController::class,'jang'])->name('jang_matrix');
    Route::resource('test', TestController::class);
    Route::resource('group_test', GroupTestsController::class);
    Route::resource('video', VideoController::class);
    Route::resource('course', CourseController::class);

//    elchilar
    Route::get('/elchi-role', [ElchilarController::class,'TgTeacher'])->name('elchi-role');

    Route::get('/elchi', [ElchilarController::class,'ElchiIndex'])->name('elchi-index');
    Route::post('/elchi-create', [ElchilarController::class,'ElchiCreate'])->name('elchi-create');
    Route::put('/elchi-update/{id}', [ElchilarController::class,'ElchiUpdate'])->name('elchi-update');
    Route::delete('/elchi-delete/{id}', [ElchilarController::class,'ElchiDelete'])->name('elchi-delete');
// end elchilar
    Route::get('/module/{course_id}',[ModuleController::class, 'index'])->name('module-index');
    Route::get('/lesson/{module_id}',[LessonsController::class, 'index'])->name('lessons-index');
    Route::get('/lesson/create/{lesson_id}',[LessonsController::class, 'create'])->name('lesson-create');
//        Route::get('/lessons/show/{lesson_id}',[LessonsController::class, 'create'])->name('lessons-create');
    Route::put('/lesson/video_dars/update/{video_id}',[LessonsController::class, 'VideoDarsUpdate'])->name('lesson-video-dars-update');
    Route::put('/lesson/group_test/{id}',[LessonsController::class, 'GroupTestUpdate'])->name('lesson-group-test-update');

    Route::post('/lesson/video_dars',[LessonsController::class, 'VideoDars'])->name('lessons-video-dars');

    Route::resource('module', ModuleController::class);
    Route::resource('lessons', LessonsController::class);
    Route::resource('raspisaniya', RaspisaniyaController::class);
    Route::get('/statistic',[StatisticController::class,'admin'])->name('statistic_admin');
    Route::get('/enter_exit',[EnterExitController::class,'index'])->name('enter-exit');
});
//'userRole:user'
Route::group(['prefix' => 'user','middleware' => ['auth','userAdminRole:old_user,teacher,user']], function () {

    Route::get('/', [AdminController::class, 'user'])->name('user');
    Route::get('/module/{course_id}',[UsersPageController::class,'index'])->name('module');
    Route::get('/lesson/{module_id}',[UsersPageController::class,'lesson'])->name('lesson');
    Route::get('/lesson-show/{lesson_id}',[UsersPageController::class,'LessonShow'])->name('lesson-show');
    Route::get('/lesson-test/{lesson_id}',[UsersPageController::class,'LessonTest'])->name('lesson-test');

    Route::get('/oraliq-test',[UsersPageController::class,'OraliqTest'])->name('oraliq-test');
    Route::post('/oraliq-check',[UsersPageController::class,'OraliqCheck'])->name('oraliq-check');

    Route::post('/first_test',[TestCheckController::class,'CheckTest'])->name('first_test');
    Route::post('/all_test',[TestCheckController::class,'AllTest'])->name('all_test');

    Route::post('/imkoniyat',[TestCheckController::class,'Imkoniyat'])->name('imkoniyat');
    Route::get('/settings')->name('settings');
    Route::get('/statistic',[StatisticController::class,'index'])->name('statistic');
    Route::get('/shogird',[ShogirdController::class,'index'])->name('shogird');
});

app/Http/Controllers/UsersAllController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;

class UsersAllController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $users = User::where('rol_id','user')->get();

        return view('admin.menu.users_all.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/admin/menu/users_all/create.blade.php
@extends('admin.layouts.action_app')
@section('title','Create Users Check')
@section('action')
    <div class="dashboard__main">
        <div class="dashboard__content bg-light-4">
            <div class="row pb-50 mb-10">
                <div class="col-auto">
                    <h1 class="text-30 lh-12 fw-700">Create users check</h1>
                </div>
            </div>

            <div class="row">
                <form action="{{route('users_check.store')}}" method="POST" class="form-group">
                    @csrf
                    <div class="row">
                        <div class="mb-3">
                            <label for="user_id" class="form-label fw-700">User ID</label>
                            <select class="form-select" placeholder="Choose User ID" id="user_id" name="user_id">
                                <option value="">--Select--</option>
                                @foreach($users as $test)
                                    <option value="{{$test->id}}">{{$test->first_name}},{{$test->last_name}} | {{$test->username}}|</option>
                                @endforeach
                            </select>
                            @error('user_id')
                            <div style="color: red" class="form-text">{{$message}}</div>
                            @enderror
                        </div>

                        <div class="mb-3 col-3 mt-30">
                            <label for="video" class="form-label fw-700">Video</label>
                            <input type="checkbox" value="1" class="" id="video" name="video">
                            @error('video')
                            <div style="color: red" class="form-text">You are must be write group test title!</div>
                            @enderror
                        </div>
                        <div class="mb-3 col-3 mt-30">
                            <label for="one_day_apteka" class="form-label fw-700">One Day Apteka</label>
                            <input type="checkbox" value="1" class="" id="one_day_apteka" name="one_day_apteka">
                            @error('one_day_apteka')
                            <div style="color: red" class="form-text">You are must be write group test title!</div>
                            @enderror
                        </div>
                    </div>

                    <button type="submit" class="btn btn-info mt-30">
                        <i class="fas fa-plus"></i>
                        Create
                    </button>
                </form>
            </div>
        </div>



        <footer class="footer -dashboard py-30">
            <div class="row items-center justify-between">
                <div class="col-auto">
                    <div class="text-13 lh-1">© 2022 Educrat. All Right Reserved.</div>
                </div>

                <div class="col-auto">
                    <div class="d-flex items-center">
                        <div class="d-flex items-center flex-wrap x-gap-20">
                            <div>
                                <a href="help-center.html" class="text-13 lh-1">Help</a>
                            </div>
                            <div>
                                <a href="terms.html" class="text-13 lh-1">Privacy Policy</a>
                            </div>
                            <div>
                                <a href="#" class="text-13 lh-1">Cookie Notice</a>
                            </div>
                            <div>
                                <a href="#" class="text-13 lh-1">Security</a>
                            </div>
                            <div>
                                <a href="terms.html" class="text-13 lh-1">Terms of Use</a>
                            </div>
                        </div>

                        <button class="button -md -rounded bg-light-4 text-light-1 ml-30">English</button>
                    </div>
                </div>
            </div>
        </footer>
    </div>
@endsection

resources/views/admin/menu/users_all/edit.blade.php
@extends('admin.layouts.action_app')
@section('title','Update Users Check')
@section('action')
    <div class="dashboard__main">
        <div class="dashboard__content bg-light-4">
            <div class="row pb-50 mb-10">
                <div class="col-auto">
                    <h1 class="text-30 lh-12 fw-700">Update Users Check</h1>
                </div>
            </div>

            <div class="row">
                <form action="{{route('users_check.update',$user_check->id)}}" method="POST" class="form-group">
                    @csrf
                    @method('PUT')
                    <div class="row">
                        <div class="mb-3">
                            <label for="user_id" class="form-label fw-700">User ID</label>
                            <select class="form-select" placeholder="Choose User ID" id="user_id" name="user_id" required>
                                <option value="">--Select--</option>
                                @foreach($users as $test)
                                    <option @if($user_check->user_id == $test->id) selected @else @endif value="{{$test->id}}">{{$test->first_name}},{{$test->last_name}} | {{$test->username}}|</option>
                                @endforeach
                            </select>
                            @error('user_id')
                            <div style="color: red" class="form-text">You are must be select group test id!</div>
                            @enderror
                        </div>

                        <div class="mb-3 col-3 mt-30">
                            <label for="video" class="form-label fw-700">Video</label>
                            <input type="checkbox" @if($user_check->video == 1) checked @else @endif value="1" class="" id="video" name="video">
                            @error('video')
                            <div style="color: red" class="form-text">You are must be write group test title!</div>
                            @enderror
                        </div>
                        <div class="mb-3 col-3 mt-30">
                            <label for="one_day_apteka" class="form-label fw-700">One Day Apteka</label>
                            <input type="checkbox" @if($user_check->one_day_apteka == 1) checked @else @endif value="1" class="" id="one_day_apteka" name="one_day_apteka">
                            @error('one_day_apteka')
                            <div style="color: red" class="form-text">You are must be write group test title!</div>
                            @enderror
                        </div>
                    </div>
                    <button type="submit" class="btn btn-info mt-30">
                        <i class="fas fa-edit"></i>
                        Update
                    </button>
                </form>
            </div>
        </div>



        <footer class="footer -dashboard py-30">
            <div class="row items-center justify-between">
                <div class="col-auto">
                    <div class="text-13 lh-1">© 2022 Educrat. All Right Reserved.</div>
                </div>

                <div class="col-auto">
                    <div class="d-flex items-center">
                        <div class="d-flex items-center flex-wrap x-gap-20">
                            <div>
                                <a href="help-center.html" class="text-13 lh-1">Help</a>
                            </div>
                            <div>
                                <a href="terms.html" class="text-13 lh-1">Privacy Policy</a>
                            </div>
                            <div>
                                <a href="#" class="text-13 lh-1">Cookie Notice</a>
                            </div>
                            <div>
                                <a href="#" class="text-13 lh-1">Security</a>
                            </div>
                            <div>
                                <a href="terms.html" class="text-13 lh-1">Terms of Use</a>
                            </div>
                        </div>

                        <button class="button -md -rounded bg-light-4 text-light-1 ml-30">English</button>
                    </div>
                </div>
            </div>
        </footer>
    </div>
@endsection

resources/views/admin/menu/users_all/index.blade.php
<?php
$t_r = 1;
?>
@extends('admin.layouts.app')
@section('title','Yangi elchilar')
@section('dashboard')
    <div class="dashboard__main">
        <div class="dashboard__content bg-light-4">
            @if(session()->has('success'))
                <div class="row">
                    <div class="col-12 ">
                        <div class="alert bg-success-1 alert-dismissible fade show pb-20 pt-20 pl-20 pr-20 rounded-8" role="alert">
                            <div class="text-success-2 lh-1 fw-500">{{session('success')}}</div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                </div>
            @elseif(session()->has('error'))
                <div class="row">
                    <div class="col-12 ">
                        <div class="alert bg-error-1 alert-dismissible fade show pb-20 pt-20 pl-20 pr-20 rounded-8" role="alert">
                            <div class="text-success-2 lh-1 fw-500">{{session('error')}}</div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                </div>
            @endif


            <div class="row pb-50 mb-10">
                <div class="col-6">
                    <h1 class="text-30 lh-12 fw-700">Yangi elchilar</h1>
                </div>
{{--                <div class="col-6 d-flex justify-content-end">--}}
{{--                    <a href="{{route('users_all.create')}}">--}}
{{--                        <button class="btn btn-success text-white">--}}
{{--                            <i class="fas fa-plus"></i>--}}
{{--                            Create--}}
{{--                        </button>--}}
{{--                    </a>--}}
{{--                </div>--}}
            </div>


            <div class="row y-gap-30">

                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">T/r</th>
{{--                        <th scope="col">Id</th>--}}
                        <th scope="col">Firstname</th>
                        <th scope="col">Lastname</th>
                        <th scope="col">Image</th>
                        <th scope="col">Phone</th>
                        <th scope="col">Username</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $test)
                        <tr>
                            <th scope="row">{{$t_r++}}</th>
{{--                            <th>{{$test->id}}</th>--}}
                            <td>{{$test->first_name}}</td>
                            <td>{{$test->last_name}}</td>
                            <td>
                                <img src="{{asset('storage/'.$test->image)}}" width="120" height="50" alt="">
                            </td>
                            <td>{{$test->phone}}</td>
                            <td>{{$test->username}}</td>
                            <td>
                                <div class="row">
                                    <div class="col-4">
                                        {{--                                      <button class="btn btn-warning text-white">--}}
                                        {{--                                         <i class="fas fa-eye"></i>--}}
                                        {{--                                         View--}}
                                        {{--                                      </button>--}}
                                    </div>
{{--                                    <div class="col-4">--}}
{{--                                        <a href="{{route('users_all.edit', ['users_check' => $test->id])}}">--}}
{{--                                            <button class="btn btn-primary text-white">--}}
{{--                                                <i class="fas fa-edit"></i>--}}
{{--                                                Update--}}
{{--                                            </button>--}}
{{--                                        </a>--}}
{{--                                    </div>--}}
{{--                                    <div class="col-4">--}}
{{--                                        <button class="btn btn-danger text-white" type="button" data-bs-toggle="modal" data-bs-target="#UsersCheckModal{{$test->id}}">--}}
{{--                                            <i class="fas fa-trash-alt"></i>--}}
{{--                                            Delete--}}
{{--                                        </button>--}}
{{--                                    </div>--}}
                                    {{--                                                                    modal delete--}}
                                    <!-- Modal -->
                                    <div class="modal fade" id="UsersCheckModal{{$test->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h1 class="modal-title fs-5" id="exampleModalLabel">Delete your {{$test->id}}</h1>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    <form action="{{route('new_user.destroy',['new_user' => $test->id])}}" method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                        <h1>Are you sure?</h1>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                                            <button type="submit" class="btn btn-danger">
                                                                <i class="fas fa-trash-alt"></i>
                                                                Delete Users Check
                                                            </button>
                                                        </div>
                                                    </form>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                    {{--                                                                   end modal delete--}}
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        @include('user.components.footer')
    </div>
@endsection

resources/views/admin/menu/users_all/show.blade.php
<?php