routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\ElchilarController;
use App\Http\Controllers\EnterExitController;
use App\Http\Controllers\GroupTestsController;
use App\Http\Controllers\IntegrationController;
use App\Http\Controllers\LessonsController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\RaspisaniyaController;
use App\Http\Controllers\ShogirdController;
use App\Http\Controllers\StatisticController;
use App\Http\Controllers\TestCheckController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\UserCheckController;
use App\Http\Controllers\UsersAllController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\UsersPageController;
use App\Http\Controllers\VideoController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => '/'], function () {
    Route::get('/register', [AuthController::class, 'registerView'])->name('register-view');
    Route::post('/register', [AuthController::class, 'register'])->name('register');

    Route::get('/', [AuthController::class, 'loginView'])->name('login');
    Route::get('/login', [AuthController::class, 'loginView'])->name('login-view');
    Route::post('/login-check', [AuthController::class, 'LoginCheck'])->name('login-check');

    Route::get('/users-region', [AuthController::class, 'ChooseRegion'])->name('users-region');

    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
});


Route::group(['prefix' => 'admin','middleware' => ['auth', 'userAdminRole:admin,assistant']], function () {
    Route::get('/', [AdminController::class, 'admin'])->name('admin');
    Route::resource('users', UsersController::class);
    Route::resource('new_user', UsersAllController::class);
    Route::resource('users_check', UserCheckController::class);
    Route::get('/integration',[IntegrationController::class,'index'])->name('integration');
    Route::get('/jang_matrix/{id}',[IntegrationController::class,'jang'])->name('jang_matrix');
    Route::resource('test', TestController::class);
    Route::resource('group_test', GroupTestsController::class);
    Route::resource('video', VideoController::class);
    Route::resource('course', CourseController::class);

//    elchilar
    Route::get('/elchi-role', [ElchilarController::class,'TgTeacher'])->name('elchi-role');

    Route::get('/elchi', [ElchilarController::class,'ElchiIndex'])->name('elchi-index');
    Route::post('/elchi-create', [ElchilarController::class,'ElchiCreate'])->name('elchi-create');
    Route::put('/elchi-update/{id}', [ElchilarController::class,'ElchiUpdate'])->name('elchi-update');
    Route::delete('/elchi-delete/{id}', [ElchilarController::class,'ElchiDelete'])->name('elchi-delete');
// end elchilar
    Route::get('/module/{course_id}',[ModuleController::class, 'index'])->name('module-index');
    Route::get('/lesson/{module_id}',[LessonsController::class, 'index'])->name('lessons-index');
    Route::get('/lesson/create/{lesson_id}',[LessonsController::class, 'create'])->name('lesson-create');
//        Route::get('/lessons/show/{lesson_id}',[LessonsController::class, 'create'])->name('lessons-create');
    Route::put('/lesson/video_dars/update/{video_id}',[LessonsController::class, 'VideoDarsUpdate'])->name('lesson-video-dars-update');
    Route::put('/lesson/group_test/{id}',[LessonsController::class, 'GroupTestUpdate'])->name('lesson-group-test-update');

    Route::post('/lesson/video_dars',[LessonsController::class, 'VideoDars'])->name('lessons-video-dars');

    Route::resource('module', ModuleController::class);
    Route::resource('lessons', LessonsController::class);
    Route::resource('raspisaniya', RaspisaniyaController::class);
    Route::get('/statistic',[StatisticController::class,'admin'])->name('statistic_admin');
    Route::get('/enter_exit',[EnterExitController::class,'index'])->name('enter-exit');
});
//'userRole:user'
Route::group(['prefix' => 'user','middleware' => ['auth','userAdminRole:old_user,teacher,user']], function () {

    Route::get('/', [AdminController::class, 'user'])->name('user');
    Route::get('/module/{course_id}',[UsersPageController::class,'index'])->name('module');
    Route::get('/lesson/{module_id}',[UsersPageController::class,'lesson'])->name('lesson');
    Route::get('/lesson-show/{lesson_id}',[UsersPageController::class,'LessonShow'])->name('lesson-show');
    Route::get('/lesson-test/{lesson_id}',[UsersPageController::class,'LessonTest'])->name('lesson-test');

    Route::get('/oraliq-test',[UsersPageController::class,'OraliqTest'])->name('oraliq-test');
    Route::post('/oraliq-check',[UsersPageController::class,'OraliqCheck'])->name('oraliq-check');

    Route::post('/first_test',[TestCheckController::class,'CheckTest'])->name('first_test');
    Route::post('/all_test',[TestCheckController::class,'AllTest'])->name('all_test');

    Route::post('/imkoniyat',[TestCheckController::class,'Imkoniyat'])->name('imkoniyat');
    Route::get('/settings')->name('settings');
    Route::get('/statistic',[StatisticController::class,'index'])->name('statistic');
    Route::get('/shogird',[ShogirdController::class,'index'])->name('shogird');
});

resources/views/admin/menu/courses/show.blade.php
@extends('admin.layouts.action_app')
@section('title','Module qo\'shish')
@section('action')
    <div class="dashboard__main">
        <div class="dashboard__content bg-light-4">
            @if(session()->has('success'))
                <div class="row">
                    <div class="col-12 ">
                        <div class="alert bg-success-1 alert-dismissible fade show pb-20 pt-20 pl-20 pr-20 rounded-8" role="alert">
                            <div class="text-success-2 lh-1 fw-500">{{session('success')}}</div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                </div>
            @elseif(session()->has('error'))
                <div class="row">
                    <div class="col-12 ">
                        <div class="alert bg-error-1 alert-dismissible fade show pb-20 pt-20 pl-20 pr-20 rounded-8" role="alert">
                            <div class="text-success-2 lh-1 fw-500">{{session('error')}}</div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                </div>
            @endif

            <div class="row pb-20 mb-10">
                <div class="col-6">
                    <h1 class="text-30 lh-12 fw-700">Kurs module</h1>
                </div>
                <div class="col-6 d-flex justify-content-end">
                        <button class="btn btn-success text-white" type="button" data-bs-toggle="modal" data-bs-target="#CourseModuleCreate">
                            <i class="fas fa-plus"></i>
                            Yaratish
                        </button>

                        <div class="modal fade" id="CourseModuleCreate" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-lg" >
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="exampleModalLabel">Siz module yaratayapsiz!</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <form action="{{route('module.store')}}" method="POST" class="form-group" enctype="multipart/form-data">
                                            @csrf
                                            <input type="hidden" class="form-control" id="course_id" value="{{$course->id}}" name="course_id">
                                            <div class="row">
                                                <div class="mb-3">
                                                    <label for="title" class="form-label fw-700">Module nomi</label>
                                                    <input type="text" class="border form-control" id="title" name="title">
                                                    @error('title')
                                                    <div style="color: red" class="form-text">{{$message}}</div>
                                                    @enderror
                                                </div>
                                            </div>
                                            <button type="submit" class="btn btn-info mt-30">
                                                <i class="fas fa-plus"></i>
                                                Yaratish
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                </div>
            </div>

            <div class="row">
                @foreach($module as $modul)
                <div class="side-content ml-10 mr-10 mt-20 col-xl-5 col-lg-5 col-md-5 col-sm-5" style="border: 2px solid #ddd; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
                    <a href="{{route('lessons-index', ['module_id' => $modul->id])}}" class="coursesCard -type-1 ">
                        <div class="h-100">
                            <div class="text-17 lh-15 fw-500 text-dark-1 mt-10">
                                {{$modul->title}}
                            </div>
                            <div class="d-flex items-center justify-content-around  pt-10">
                                <div class="d-flex items-center">
                                    <div class="mr-8">
                                        <img src="{{asset('assets/img/coursesCards/icons/1.svg')}}" alt="icon">
                                    </div>
                                    <div class="text-14 lh-1">6 lesson</div>
                                </div>

                                <div class="d-flex items-center">
                                    <div class="mr-8">
                                        <img src="{{asset('assets/img/coursesCards/icons/2.svg')}}" alt="icon">
                                    </div>
                                    <div class="text-14 lh-1">3h 56m</div>
                                </div>
                            </div>
                        </div>
                    </a>
                    <div class="row py-15">
                        <div class="col-6 text-center">
                            <button class="btn btn-primary text-white" type="button" data-bs-toggle="modal" data-bs-target="#CourseModalEdit{{$modul->id}}">
                                <i class="fas fa-edit"></i>
                                Tahrirlash
                            </button>
                            {{--                                modal edit--}}
                            <!-- Modal -->
                            <div class="modal fade" id="CourseModalEdit{{$modul->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-lg" >
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h1 class="modal-title fs-5" id="exampleModalLabel">Siz {{$modul->title}} kursini tahrirlamoqchisiz!</h1>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <form action="{{route('module.update',$modul->id)}}" method="POST" class="form-group" enctype="multipart/form-data">
                                                @csrf
                                                @method('PUT')
                                                <input type="hidden" value="{{$modul->course_id}}" class="form-control" id="course_id" name="course_id">
                                                <div class="row">
                                                    <div class="mb-3">
                                                        <label for="title" class="form-label fw-700">Module nomi</label>
                                                        <input type="text" value="{{$modul->title}}" class="form-control" id="title" name="title">
                                                        @error('title')
                                                        <div style="color: red" class="form-text">{{$message}}</div>
                                                        @enderror
                                                    </div>

                                                </div>
                                                <button type="submit" class="btn btn-primary mt-30">
                                                    <i class="fas fa-edit"></i>
                                                    Tahrirlash
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {{--                             end edit modal--}}
                        </div>
                        <div class="col-6 text-center">
                            <button class="btn btn-danger text-white" type="button" data-bs-toggle="modal" data-bs-target="#CourseModal{{$modul->id}}">
                                <i class="fas fa-trash-alt"></i>
                                O'chirish
                            </button>
                            {{--                                modal delete--}}
                            <div class="modal fade" id="CourseModal{{$modul->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog ">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h1 class="modal-title fs-5" id="exampleModalLabel">Siz {{$modul->title}} kursini o'chirmoqchisiz!</h1>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <form action="{{route('module.destroy',['module' => $modul->id])}}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <input type="hidden" value="{{$modul->course_id}}" class="form-control" id="course_id" name="course_id">
                                                <h3>Sizni ishonchingiz komilmi!</h3>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Yopish</button>
                                                    <button type="submit" class="btn btn-danger">
                                                        <i class="fas fa-trash-alt"></i>
                                                        Modulni o'chirish
                                                    </button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {{--                               end modal delete--}}
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
        </div>



        <footer class="footer -dashboard py-30">
            <div class="row items-center justify-between">
                <div class="col-auto">
                    <div class="text-13 lh-1">© 2022 Educrat. All Right Reserved.</div>
                </div>

                <div class="col-auto">
                    <div class="d-flex items-center">
                        <div class="d-flex items-center flex-wrap x-gap-20">
                            <div>
                                <a href="help-center.html" class="text-13 lh-1">Help</a>
                            </div>
                            <div>
                                <a href="terms.html" class="text-13 lh-1">Privacy Policy</a>
                            </div>
                            <div>
                                <a href="#" class="text-13 lh-1">Cookie Notice</a>
                            </div>
                            <div>
                                <a href="#" class="text-13 lh-1">Security</a>
                            </div>
                            <div>
                                <a href="terms.html" class="text-13 lh-1">Terms of Use</a>
                            </div>
                        </div>

                        <button class="button -md -rounded bg-light-4 text-light-1 ml-30">English</button>
                    </div>
                </div>
            </div>
        </footer>
    </div>
@endsection