routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\ElchilarController;
use App\Http\Controllers\EnterExitController;
use App\Http\Controllers\GroupTestsController;
use App\Http\Controllers\IntegrationController;
use App\Http\Controllers\LessonsController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\RaspisaniyaController;
use App\Http\Controllers\ShogirdController;
use App\Http\Controllers\StatisticController;
use App\Http\Controllers\TestCheckController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\UserCheckController;
use App\Http\Controllers\UsersAllController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\UsersPageController;
use App\Http\Controllers\VideoController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => '/'], function () {
    Route::get('/register', [AuthController::class, 'registerView'])->name('register-view');
    Route::post('/register', [AuthController::class, 'register'])->name('register');

    Route::get('/', [AuthController::class, 'loginView'])->name('login');
    Route::get('/login', [AuthController::class, 'loginView'])->name('login-view');
    Route::post('/login-check', [AuthController::class, 'LoginCheck'])->name('login-check');

    Route::get('/users-region', [AuthController::class, 'ChooseRegion'])->name('users-region');

    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
});


Route::group(['prefix' => 'admin','middleware' => ['auth', 'userAdminRole:admin,assistant']], function () {
    Route::get('/', [AdminController::class, 'admin'])->name('admin');
    Route::resource('users', UsersController::class);
    Route::resource('new_user', UsersAllController::class);
    Route::resource('users_check', UserCheckController::class);
    Route::get('/integration',[IntegrationController::class,'index'])->name('integration');
    Route::get('/jang_matrix/{id}',[IntegrationController::class,'jang'])->name('jang_matrix');
    Route::resource('test', TestController::class);
    Route::resource('group_test', GroupTestsController::class);
    Route::resource('video', VideoController::class);
    Route::resource('course', CourseController::class);

//    elchilar
    Route::get('/elchi-role', [ElchilarController::class,'TgTeacher'])->name('elchi-role');

    Route::get('/elchi', [ElchilarController::class,'ElchiIndex'])->name('elchi-index');
    Route::post('/elchi-create', [ElchilarController::class,'ElchiCreate'])->name('elchi-create');
    Route::put('/elchi-update/{id}', [ElchilarController::class,'ElchiUpdate'])->name('elchi-update');
    Route::delete('/elchi-delete/{id}', [ElchilarController::class,'ElchiDelete'])->name('elchi-delete');
// end elchilar
    Route::get('/module/{course_id}',[ModuleController::class, 'index'])->name('module-index');
    Route::get('/lesson/{module_id}',[LessonsController::class, 'index'])->name('lessons-index');
    Route::get('/lesson/create/{lesson_id}',[LessonsController::class, 'create'])->name('lesson-create');
//        Route::get('/lessons/show/{lesson_id}',[LessonsController::class, 'create'])->name('lessons-create');
    Route::put('/lesson/video_dars/update/{video_id}',[LessonsController::class, 'VideoDarsUpdate'])->name('lesson-video-dars-update');
    Route::put('/lesson/group_test/{id}',[LessonsController::class, 'GroupTestUpdate'])->name('lesson-group-test-update');

    Route::post('/lesson/video_dars',[LessonsController::class, 'VideoDars'])->name('lessons-video-dars');

    Route::resource('module', ModuleController::class);
    Route::resource('lessons', LessonsController::class);
    Route::resource('raspisaniya', RaspisaniyaController::class);
    Route::get('/statistic',[StatisticController::class,'admin'])->name('statistic_admin');
    Route::get('/enter_exit',[EnterExitController::class,'index'])->name('enter-exit');
});
//'userRole:user'
Route::group(['prefix' => 'user','middleware' => ['auth','userAdminRole:old_user,teacher,user']], function () {

    Route::get('/', [AdminController::class, 'user'])->name('user');
    Route::get('/module/{course_id}',[UsersPageController::class,'index'])->name('module');
    Route::get('/lesson/{module_id}',[UsersPageController::class,'lesson'])->name('lesson');
    Route::get('/lesson-show/{lesson_id}',[UsersPageController::class,'LessonShow'])->name('lesson-show');
    Route::get('/lesson-test/{lesson_id}',[UsersPageController::class,'LessonTest'])->name('lesson-test');

    Route::get('/oraliq-test',[UsersPageController::class,'OraliqTest'])->name('oraliq-test');
    Route::post('/oraliq-check',[UsersPageController::class,'OraliqCheck'])->name('oraliq-check');

    Route::post('/first_test',[TestCheckController::class,'CheckTest'])->name('first_test');
    Route::post('/all_test',[TestCheckController::class,'AllTest'])->name('all_test');

    Route::post('/imkoniyat',[TestCheckController::class,'Imkoniyat'])->name('imkoniyat');
    Route::get('/settings')->name('settings');
    Route::get('/statistic',[StatisticController::class,'index'])->name('statistic');
    Route::get('/shogird',[ShogirdController::class,'index'])->name('shogird');
});

app/Models/Video.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Video extends Model
{
    use HasFactory;
    protected $table = 'lms_videos';
    protected $primaryKey = 'id';

    protected $fillable = ['url','content','image','lesson_id'];

}

app/Http/Controllers/VideoController.php
<?php

namespace App\Http\Controllers;

use App\Models\GroupTest;
use App\Models\Video;
use Illuminate\Http\Request;

class VideoController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $video = Video::orderBy('id','asc')->get();
        return view('admin.menu.videos.index' ,compact('video'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $group_test = GroupTest::select('id','title')->get();
        return view('admin.menu.videos.create' ,compact('group_test'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'title'=>'required',
            'url'=>'required',
            'group_test_id'=>'required',
            'content_type'=>'required',
        ]);

        $data = new Video();
        $data->title = $request->title;
        $data->url = $request->url;
        $data->group_test_id = $request->group_test_id;
        $data->content = $request->content_type;


        if (!$data->save()){
            return redirect(route('video.create'))->with('error','Video created error!');
        }
        return redirect(route('video.index'))->with('success','Video successfully created!');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $video = Video::findOrFail($id);
        $group_test = GroupTest::select('id','title')->get();
//        return $video;
//        $video = Video::where('id',$id)->get();
        return view('admin.menu.videos.edit',compact('video','group_test'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $user_data = Video::find($id);
        $input = $request->all();
        $user_data->update($input);
        $request->validate([
            'title'=>'required',
            'url'=>'required',
            'group_test_id'=>'required',
            'content_type'=>'required',
        ]);
        $user_data->title = $request->title;
        $user_data->url = $request->url;
        $user_data->group_test_id = $request->group_test_id;
        $user_data->content = $request->content_type;


        if (!$user_data->save()){
            return redirect(route('video.update'))->with('error','Video updated error');
        }
        return redirect(route('video.index'))->with('success','Video successfully updated!');

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        Video::destroy($id);
        return redirect(route('video.index'))->with('success', 'Video successfully deleted!');
    }
}

resources/views/admin/menu/videos/create.blade.php
@extends('admin.layouts.action_app')
@section('title','Videos')
@section('action')
    <div class="dashboard__main">
        <div class="dashboard__content bg-light-4">
            <div class="row pb-50 mb-10">
                <div class="col-auto">
                    <h1 class="text-30 lh-12 fw-700">Videos</h1>
                </div>
            </div>

            <div class="row">
                <form action="{{route('video.store')}}" method="POST" class="form-group">
                    @csrf
                    <div class="row">
                        <div class="mb-3">
                            <label for="title" class="form-label fw-700">Title</label>
                            <input type="text" class="form-control" id="title" name="title">
                            @error('title')
                            <div style="color: red" class="form-text">You are must be write question title!</div>
                            @enderror
                        </div>
                        <div class="col-6">
                            <div class="mb-3 mt-30">
                                <label for="url" class="form-label fw-700">URL</label>
                                <input type="text" class="form-control" id="url" name="url">
                            </div>
                            @error('url')
                            <div style="color: red" class="form-text">You are must be write url!</div>
                            @enderror
                        </div>

                        <div class="mb-3 mt-30 col-6">
                            <label for="group_test_id" class="form-label fw-700">Group Test ID</label>
                            <select class="form-select" placeholder="Choose Group Test ID" id="group_test_id" name="group_test_id" required>
                                <option value="">--Select--</option>
                                @foreach($group_test as $test)
                                    <option value="{{$test->id}}">{{$test->title}}</option>
                                @endforeach
                            </select>
                            @error('group_test_id')
                            <div style="color: red" class="form-text">You are must be select group test id!</div>
                            @enderror
                        </div>
                        <div class="col-12">
                             <div class="mb-3 mt-30 contact-form">
                                 <label class="text-16 lh-1 fw-500 text-dark-1 mb-10">Textarea</label>
                                 <textarea placeholder="Content..." class="form-control" rows="7" name="content_type" style="outline: none;width: 100%;background-color: transparent; border-radius: 8px;border: 1px solid #DDDDDD; font-size: 15px;line-height: 1.5;padding: 15px 22px;transition: all 0.15s cubic-bezier(0.165, 0.84, 0.44, 1);"></textarea>
                             </div>
                            @error('content_type')
                            <div style="color: red" class="form-text">You are must be write content!</div>
                            @enderror
                        </div>

                    </div>
                    <button type="submit" class="btn btn-info mt-30">
                        <i class="fas fa-plus"></i>
                        Create
                    </button>
                </form>
            </div>
        </div>



        <footer class="footer -dashboard py-30">
            <div class="row items-center justify-between">
                <div class="col-auto">
                    <div class="text-13 lh-1">© 2022 Educrat. All Right Reserved.</div>
                </div>

                <div class="col-auto">
                    <div class="d-flex items-center">
                        <div class="d-flex items-center flex-wrap x-gap-20">
                            <div>
                                <a href="help-center.html" class="text-13 lh-1">Help</a>
                            </div>
                            <div>
                                <a href="terms.html" class="text-13 lh-1">Privacy Policy</a>
                            </div>
                            <div>
                                <a href="#" class="text-13 lh-1">Cookie Notice</a>
                            </div>
                            <div>
                                <a href="#" class="text-13 lh-1">Security</a>
                            </div>
                            <div>
                                <a href="terms.html" class="text-13 lh-1">Terms of Use</a>
                            </div>
                        </div>

                        <button class="button -md -rounded bg-light-4 text-light-1 ml-30">English</button>
                    </div>
                </div>
            </div>
        </footer>
    </div>
@endsection

resources/views/admin/menu/videos/edit.blade.php
@extends('admin.layouts.action_app')
@section('title','Update videos')
@section('action')
    <div class="dashboard__main">
        <div class="dashboard__content bg-light-4">
            <div class="row pb-50 mb-10">
                <div class="col-auto">
                    <h1 class="text-30 lh-12 fw-700">Update videos</h1>
                </div>
            </div>

            <div class="row">
                <form action="{{route('video.update',$video->id)}}" method="POST" class="form-group">
                    @csrf
                    @method('PUT')
                    <div class="row">
                        <div class="mb-3">
                            <label for="title" class="form-label fw-700">Title</label>
                            <input type="text" value="{{$video->title}}" class="form-control" id="title" name="title">
                            @error('title')
                            <div style="color: red" class="form-text">You are must be write question title!</div>
                            @enderror
                        </div>
                        <div class="col-6">
                            <div class="mb-3 mt-30">
                                <label for="url" class="form-label fw-700">URL</label>
                                <input type="text" value="{{$video->url}}" class="form-control" id="url" name="url">
                            </div>
                            @error('url')
                            <div style="color: red" class="form-text">You are must be write url!</div>
                            @enderror
                        </div>

                        <div class="mb-3 mt-30 col-6">
                            <label for="group_test_id" class="form-label fw-700">Group Test ID</label>
                            <select class="form-select" placeholder="Choose Group Test ID" id="group_test_id" name="group_test_id" required>
                                <option value="">--Select--</option>
                                @foreach($group_test as $test)
                                    <option @if($video->group_test_id == $test->id) selected @else @endif value="{{$test->id}}">{{$test->title}}</option>
                                @endforeach
                            </select>
                            @error('group_test_id')
                            <div style="color: red" class="form-text">You are must be select group test id!</div>
                            @enderror
                        </div>
                        <div class="col-12">
                            <div class="mb-3 mt-30 contact-form">
                                <label class="text-16 lh-1 fw-500 text-dark-1 mb-10">Textarea</label>
                                <textarea placeholder="Content..." class="form-control" rows="7" name="content_type" style="outline: none;width: 100%;background-color: transparent; border-radius: 8px;border: 1px solid #DDDDDD; font-size: 15px;line-height: 1.5;padding: 15px 22px;transition: all 0.15s cubic-bezier(0.165, 0.84, 0.44, 1);">{{$video->content}}</textarea>
                            </div>
                            @error('content_type')
                            <div style="color: red" class="form-text">You are must be write content!</div>
                            @enderror
                        </div>

                    </div>
                    <button type="submit" class="btn btn-info mt-30">
                        <i class="fas fa-edit"></i>
                        Update
                    </button>
                </form>
            </div>
        </div>



        <footer class="footer -dashboard py-30">
            <div class="row items-center justify-between">
                <div class="col-auto">
                    <div class="text-13 lh-1">© 2022 Educrat. All Right Reserved.</div>
                </div>

                <div class="col-auto">
                    <div class="d-flex items-center">
                        <div class="d-flex items-center flex-wrap x-gap-20">
                            <div>
                                <a href="help-center.html" class="text-13 lh-1">Help</a>
                            </div>
                            <div>
                                <a href="terms.html" class="text-13 lh-1">Privacy Policy</a>
                            </div>
                            <div>
                                <a href="#" class="text-13 lh-1">Cookie Notice</a>
                            </div>
                            <div>
                                <a href="#" class="text-13 lh-1">Security</a>
                            </div>
                            <div>
                                <a href="terms.html" class="text-13 lh-1">Terms of Use</a>
                            </div>
                        </div>

                        <button class="button -md -rounded bg-light-4 text-light-1 ml-30">English</button>
                    </div>
                </div>
            </div>
        </footer>
    </div>
@endsection

resources/views/admin/menu/videos/index.blade.php
@extends('admin.layouts.app')
@section('title','Video')
@section('dashboard')
    <div class="dashboard__main">
        <div class="dashboard__content bg-light-4">
            @if(session()->has('success'))
                <div class="row">
                    <div class="col-12 ">
                        <div class="alert bg-success-1 alert-dismissible fade show pb-20 pt-20 pl-20 pr-20 rounded-8" role="alert">
                            <div class="text-success-2 lh-1 fw-500">{{session('success')}}</div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                </div>
            @elseif(session()->has('error'))
                <div class="row">
                    <div class="col-12 ">
                        <div class="alert bg-error-1 alert-dismissible fade show pb-20 pt-20 pl-20 pr-20 rounded-8" role="alert">
                            <div class="text-success-2 lh-1 fw-500">{{session('error')}}</div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                </div>
            @endif


            <div class="row pb-50 mb-10">
                <div class="col-6">
                    <h1 class="text-30 lh-12 fw-700">Video</h1>
                </div>
                <div class="col-6 d-flex justify-content-end">
                    <a href="{{route('video.create')}}">
                        <button class="btn btn-success text-white">
                            <i class="fas fa-plus"></i>
                            Create
                        </button>
                    </a>
                </div>
            </div>


            <div class="row y-gap-30">

                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Title</th>
                        <th scope="col">URL</th>
                        <th scope="col">Group_Test_ID</th>
                        <th scope="col">Content</th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($video as $test)
                        <tr>
                            <th scope="row">{{$test->id}}</th>
                            <td>{{$test->title}}</td>
                            <td>{{$test->url}}</td>
                            <td>{{$test->group_test_id}}</td>
                            <td>{{$test->content}}</td>
                            <td>
                                <div class="row">
                                    <div class="col-4">
                                        {{--                                    <button class="btn btn-warning text-white">--}}
                                        {{--                                        <i class="fas fa-eye"></i>--}}
                                        {{--                                        View--}}
                                        {{--                                    </button>--}}
                                    </div>
                                    <div class="col-4">
                                        <a href="{{route('video.edit', ['video' => $test->id])}}">
                                            <button class="btn btn-primary text-white">
                                                <i class="fas fa-edit"></i>
                                                Update
                                            </button>
                                        </a>
                                    </div>
                                    <div class="col-4">
                                        <button class="btn btn-danger text-white" type="button" data-bs-toggle="modal" data-bs-target="#VideoModal{{$test->id}}">
                                            <i class="fas fa-trash-alt"></i>
                                            Delete
                                        </button>
                                    </div>
                                    {{--                                modal delete--}}
                                    <!-- Modal -->
                                    <div class="modal fade" id="VideoModal{{$test->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h1 class="modal-title fs-5" id="exampleModalLabel">Delete your {{$test->title}}</h1>
                                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    <form action="{{route('video.destroy',['video' => $test->id])}}" method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                        <h1>Are you sure?</h1>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                                            <button type="submit" class="btn btn-danger">
                                                                <i class="fas fa-trash-alt"></i>
                                                                Delete Tests
                                                            </button>
                                                        </div>
                                                    </form>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                    {{--                               end modal delete--}}
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>

        </div>

        <footer class="footer -dashboard py-30">
            <div class="row items-center justify-between">
                <div class="col-auto">
                    <div class="text-13 lh-1">© 2022 Educrat. All Right Reserved.</div>
                </div>

                <div class="col-auto">
                    <div class="d-flex items-center">
                        <div class="d-flex items-center flex-wrap x-gap-20">
                            <div>
                                <a href="help-center.html" class="text-13 lh-1">Help</a>
                            </div>
                            <div>
                                <a href="terms.html" class="text-13 lh-1">Privacy Policy</a>
                            </div>
                            <div>
                                <a href="#" class="text-13 lh-1">Cookie Notice</a>
                            </div>
                            <div>
                                <a href="#" class="text-13 lh-1">Security</a>
                            </div>
                            <div>
                                <a href="terms.html" class="text-13 lh-1">Terms of Use</a>
                            </div>
                        </div>

                        <button class="button -md -rounded bg-light-4 text-light-1 ml-30">English</button>
                    </div>
                </div>
            </div>
        </footer>
    </div>
@endsection

resources/views/admin/menu/videos/show.blade.php
<?php